stages:
  - build


build:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  tags:
    - linux
  services:
    - name: 'docker:20.10.12-dind'
      command: ["--tls=false"]
  script:
    - |
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest"  .
    - docker push "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME"